/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        dark: '#0a0e27',
        'dark-secondary': '#1a1f3a',
        accent: '#00ff00',
        'accent-dark': '#00cc00',
        'accent-light': '#33ff33',
        metallic: '#8b8b8b',
        'metallic-light': '#b8b8b8',
      },
      fontFamily: {
        poppins: ['Poppins', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        sport: ['Poppins', 'sans-serif'],
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.875rem', { lineHeight: '1.25rem' }],
        base: ['1rem', { lineHeight: '1.5rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
      },
      spacing: {
        safe: 'max(1rem, env(safe-area-inset-left))',
        'safe-right': 'max(1rem, env(safe-area-inset-right))',
        'safe-bottom': 'max(1rem, env(safe-area-inset-bottom))',
        'safe-top': 'max(1rem, env(safe-area-inset-top))',
      },
      borderRadius: {
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      opacity: {
        5: '0.05',
        10: '0.1',
        15: '0.15',
        20: '0.2',
        25: '0.25',
        30: '0.3',
        40: '0.4',
        50: '0.5',
        60: '0.6',
        70: '0.7',
        75: '0.75',
        80: '0.8',
        90: '0.9',
        95: '0.95',
      },
      backdropBlur: {
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
      },
      boxShadow: {
        sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        md: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
        lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
        xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
        'inner-lg': 'inset 0 10px 15px -3px rgba(0, 0, 0, 0.1)',
      },
      animation: {
        spin: 'spin 1s linear infinite',
        pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        bounce: 'bounce 1s infinite',
        fadeIn: 'fadeIn 0.3s ease-in',
        slideUp: 'slideUp 0.3s ease-out',
        slideDown: 'slideDown 0.3s ease-out',
      },
      keyframes: {
        spin: {
          to: { transform: 'rotate(360deg)' },
        },
        pulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        bounce: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-4px)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        slideUp: {
          from: {
            transform: 'translateY(10px)',
            opacity: '0',
          },
          to: {
            transform: 'translateY(0)',
            opacity: '1',
          },
        },
        slideDown: {
          from: {
            transform: 'translateY(-10px)',
            opacity: '0',
          },
          to: {
            transform: 'translateY(0)',
            opacity: '1',
          },
        },
      },
      transitionDuration: {
        250: '250ms',
        350: '350ms',
        500: '500ms',
      },
      screens: {
        xs: '375px',
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/line-clamp'),
  ],
  safelist: [
    // Colors
    'text-accent',
    'text-red-400',
    'text-red-500',
    'text-green-400',
    'text-green-500',
    'text-blue-400',
    'text-blue-500',
    'text-yellow-400',
    'text-yellow-500',
    'text-purple-400',
    'text-orange-400',
    'text-cyan-400',
    'text-metallic',
    'text-metallic-light',
    'text-dark',
    'bg-accent',
    'bg-red-400',
    'bg-red-500',
    'bg-green-400',
    'bg-green-500',
    'bg-green-600',
    'bg-blue-400',
    'bg-blue-500',
    'bg-blue-600',
    'bg-yellow-400',
    'bg-yellow-500',
    'bg-purple-400',
    'bg-orange-400',
    'bg-cyan-400',
    'bg-dark',
    'bg-dark-secondary',
    'bg-metallic',
    // Opacity
    'bg-opacity-5',
    'bg-opacity-10',
    'bg-opacity-15',
    'bg-opacity-20',
    'bg-opacity-25',
    'bg-opacity-30',
    'bg-opacity-40',
    'bg-opacity-50',
    'bg-opacity-60',
    'bg-opacity-70',
    'bg-opacity-75',
    'bg-opacity-80',
    'bg-opacity-90',
    'border-opacity-20',
    'border-opacity-30',
    'border-opacity-50',
    // Border
    'border-accent',
    'border-red-400',
    'border-red-500',
    'border-green-400',
    'border-green-500',
    'border-blue-400',
    'border-metallic',
    // Hover states
    'hover:bg-dark',
    'hover:bg-dark-secondary',
    'hover:bg-accent',
    'hover:bg-red-500',
    'hover:bg-red-600',
    'hover:bg-green-400',
    'hover:bg-green-500',
    'hover:bg-green-600',
    'hover:bg-blue-500',
    'hover:bg-blue-600',
    'hover:text-accent',
    'hover:text-metallic-light',
    'hover:border-accent',
    'hover:border-metallic',
    'hover:border-opacity-50',
  ],
}